// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// This file contains Firebase configuration options for different platforms.
// It is auto-generated and should not be edited manually.
// Use DefaultFirebaseOptions.currentPlatform to get the appropriate options for the current platform.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfpVnzNCn8_pbEyQ3X4I9aOkBzSe7-vXc',
    appId: '1:990221643407:web:03eb4c3ed8615436c08afa',
    messagingSenderId: '990221643407',
    projectId: 'servd-4430e',
    authDomain: 'servd-4430e.firebaseapp.com',
    storageBucket: 'servd-4430e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyD2-5T6W0NeVM4CHsnLKLKbN2CQOgj6M',
    appId: '1:990221643407:android:1966dbc27696a500c08afa',
    messagingSenderId: '990221643407',
    projectId: 'servd-4430e',
    storageBucket: 'servd-4430e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0_pTD1wJ1PZy1aNCkIvNn8WzGtqmcUTU',
    appId: '1:990221643407:ios:562047e29cd8b17dc08afa',
    messagingSenderId: '990221643407',
    projectId: 'servd-4430e',
    storageBucket: 'servd-4430e.firebasestorage.app',
    iosBundleId: 'com.example.served',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0_pTD1wJ1PZy1aNCkIvNn8WzGtqmcUTU',
    appId: '1:990221643407:ios:562047e29cd8b17dc08afa',
    messagingSenderId: '990221643407',
    projectId: 'servd-4430e',
    storageBucket: 'servd-4430e.firebasestorage.app',
    iosBundleId: 'com.example.served',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfpVnzNCn8_pbEyQ3X4I9aOkBzSe7-vXc',
    appId: '1:990221643407:web:4b395912952e4110c08afa',
    messagingSenderId: '990221643407',
    projectId: 'servd-4430e',
    authDomain: 'servd-4430e.firebaseapp.com',
    storageBucket: 'servd-4430e.firebasestorage.app',
  );

}